### ISSUE TITLE
Cannot connect to MySQL

### ISSUE THREAD

**Issue by juancresc** [irusri/Extract-intron-from-gff3#1]
I got this, but MySQL is up and running, double check user, pass and dbname.

> "my" variable $AUTH masks earlier declaration in same scope at bp_bulk_load_gff.pl line 656.
> "my" variable $db masks earlier declaration in same scope at bp_bulk_load_gff.pl line 666.
> This operation will delete all existing data in database gbrowse_database.  Continue? y
> Use of uninitialized value $DBD in string eq at bp_bulk_load_gff.pl line 251.
> DBI connect('gbrowse_database','root',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/Bio/DB/GFF/Adaptor/dbi/caching_handle.pm line 134
> 
> ------------- EXCEPTION: Bio::Root::Exception -------------
> MSG: Can't connect to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
> STACK: Error::throw
> STACK: Bio::Root::Root::throw /usr/share/perl5/Bio/Root/Root.pm:472
> STACK: Bio::DB::GFF::Adaptor::dbi::caching_handle::new /usr/share/perl5/Bio/DB/GFF/Adaptor/dbi/caching_handle.pm:88
> STACK: Bio::DB::GFF::Adaptor::dbi::new /usr/share/perl5/Bio/DB/GFF/Adaptor/dbi.pm:97
> STACK: Bio::DB::GFF::Adaptor::dbi::mysql::new /usr/share/perl5/Bio/DB/GFF/Adaptor/dbi/mysql.pm:269
> STACK: Bio::DB::GFF::new /usr/share/perl5/Bio/DB/GFF.pm:740
> STACK: bp_bulk_load_gff.pl:318
> -----------------------------------------------------------

**Comment by irusri** [comment]
Have you checked your /var/run/mysqld/mysqld.sock exist? otherwise please do following steps if you are using Unix system.
`ln -s  /tmp/mysqld/mysqld.sock /var/run/mysqld/mysqld.sock ` 
`sudo chown -R mysql:mysql  /var/run/mysqld/ .`
 `service mysql restart `

**Comment by juancresc** [comment]
my wrong, green light to delete
