### ISSUE TITLE
ImportError: No module named misopy

### ISSUE THREAD

**Issue by LujingF** [irusri/Extract-intron-from-gff3#2]
thanks for sharing your scripts. however, when I use the extract_intron_gff3_from_gff3.py to extract intron gff3 file, the script came an error ''ImportError: No module named misopy"

**Comment by irusri** [comment]
Could you try `pip install misopy` before running the script? For more detail take a look at the [documentation](https://miso.readthedocs.io/en/fastmiso/).

**Comment by LujingF** [comment]
thank you very much and I appologized for my late replies. well, I have installed the misopy. But the new problem is "Possible precedence issue with control flow operator at /usr/share/perl5/Bio/DB/IndexedBase.pm line 791". This is happend  when I using Bio::DB::Fasta. I installed the bioperl by using "apt-get install bioperl".  Any suggestions? many thanks.

**Comment by LujingF** [comment]
thank you very much and I appologized for my late replies. well, I have installed the misopy. But the new problem is "Possible precedence issue with control flow operator at /usr/share/perl5/Bio/DB/IndexedBase.pm line 791". This is happend when I using Bio::DB::Fasta. I installed the bioperl by using "apt-get install bioperl". Any suggestions? many thanks.

**Comment by irusri** [comment]
In this case, you need to install `Bio::DB`. However, if you use `extract_intron_gff3_from_gff3.py` Python script, you do not need Perl modules to be installed.
